language: python
sudo: enabled
services:
    - mysql
python:
    - "3.7"
env:
    global:
     - TRAVIS=true
before_install:
    - mysql -e 'CREATE DATABASE IF NOT EXISTS mysql;'
    # - mv configs.example.json configs.json
# command to install dependencies
install:
    - pip install -r requirements.txt
    
script:
    - cd ./shuimu_backends
    - python manage.py makemigrations
    - python manage.py migrate
    # - python manage.py runserver
    - python manage.py test