language: python
sudo: enabled
services:
    - mysql
python:
    - "3.7"
env:
    global:
     - TRAVIS=true
before_install:
    - mysql -e 'CREATE DATABASE IF NOT EXISTS mysql;'
    # - mv configs.example.json configs.json
# command to install dependencies
install:
    - pip install -r requirements.txt
    
script:
    python ./shuimu_backends/manage.py makemigrations
    python ./shuimu_backends/manage.py migrate
    python ./shuimu_backends/manage.py runserver
    python ./shuimu_backends/manage.py test